Token = "abab"
ServerHost = "1.1.1.1"
ServerPort = 10001

[Stun]
Type = "simple"
Host = "1.1.1.1"
PrimaryPort = 10002
SecondaryPort = 10003

[Net]
Tun = "tun9"
IP = "192.168.58.12/24"
AllowNets = ["192.168.56.100/32"]
